export type Product = {
  id: string;
  name: string;
  slug: string;
  price: number;
  compareAtPrice?: number;
  category: string;
  subcategory?: string;
  image: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  badge?: string;
  description: string;
  variants?: {
    type: string;
    options: string[];
  }[];
  // For SfGallery - multiple images
  images?: { src: string; alt: string }[];
};

// Farm supply themed products - Prairie Supply Co. (UFA-inspired)
export const products: Product[] = [
  // === FEED & NUTRITION (8 products) ===
  {
    id: "p1",
    name: "Premium Cattle Mineral Block 50lb",
    slug: "premium-cattle-mineral-block-50lb",
    price: 28.99,
    compareAtPrice: 34.99,
    category: "Feed & Nutrition",
    subcategory: "Livestock Minerals",
    image: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800&q=80",
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    badge: "Best Seller",
    description: "High-quality trace mineral supplement for cattle. Supports growth, reproduction and overall herd health.",
    variants: [{ type: "Size", options: ["25lb", "50lb"] }],
  },
  {
    id: "p7",
    name: "Purina Horse Feed - Strategy 50lb",
    slug: "purina-horse-feed-strategy",
    price: 32.49,
    category: "Feed & Nutrition",
    subcategory: "Horse Feed",
    image: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800&q=80",
    rating: 4.4,
    reviewCount: 78,
    inStock: true,
    description: "Complete nutrition for performance and pleasure horses. Pellet form for easy feeding.",
  },
  {
    id: "p9",
    name: "Bayer Baytril 100 Antimicrobial 100ml",
    slug: "bayer-baytril-100-antimicrobial",
    price: 89.50,
    category: "Feed & Nutrition",
    subcategory: "Animal Health",
    image: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800&q=80",
    rating: 4.9,
    reviewCount: 34,
    inStock: true,
    badge: "Rx Required",
    description: "Broad spectrum antibiotic for cattle and swine. For the treatment of respiratory disease.",
  },
  {
    id: "p11",
    name: "MasterFeeds 14% Beef Grower Pellet 25kg",
    slug: "masterfeeds-14-beef-grower-pellet",
    price: 19.99,
    category: "Feed & Nutrition",
    subcategory: "Cattle Feed",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
    rating: 4.6,
    reviewCount: 91,
    inStock: true,
    description: "High energy pellet formulated for growing beef cattle on pasture or in feedlot.",
  },
  {
    id: "p12",
    name: "Hi-Pro Feeds 16% Layer Pellet 20kg",
    slug: "hi-pro-layer-pellet-20kg",
    price: 16.49,
    category: "Feed & Nutrition",
    subcategory: "Poultry Feed",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    badge: "Best Seller",
    description: "Complete layer feed with added calcium for strong eggshells and consistent production.",
  },
  {
    id: "p13",
    name: "Sweetlix Bloat Guard Pressed Block",
    slug: "sweetlix-bloat-guard-block",
    price: 24.99,
    category: "Feed & Nutrition",
    subcategory: "Livestock Minerals",
    image: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800&q=80",
    rating: 4.5,
    reviewCount: 67,
    inStock: true,
    description: "Prevents bloat in cattle grazing on lush alfalfa or clover pastures.",
  },
  {
    id: "p14",
    name: "Blue Seal 12% Textured Horse Feed 50lb",
    slug: "blue-seal-12-textured-horse-feed",
    price: 27.99,
    category: "Feed & Nutrition",
    subcategory: "Horse Feed",
    image: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800&q=80",
    rating: 4.8,
    reviewCount: 83,
    inStock: true,
    description: "Palatable textured feed for mature horses in light to moderate work.",
  },
  {
    id: "p15",
    name: "Manna Pro Calf Milk Replacer 25lb",
    slug: "manna-pro-calf-milk-replacer",
    price: 38.50,
    category: "Feed & Nutrition",
    subcategory: "Calf Feed",
    image: "https://picsum.photos/id/251/600/600",
    rating: 4.3,
    reviewCount: 45,
    inStock: true,
    description: "High quality milk replacer for raising healthy replacement heifers.",
  },

  // === FENCING & LIVESTOCK (8 products) ===
  {
    id: "p2",
    name: "Gallagher Electric Fencing Kit - 1 Mile",
    slug: "gallagher-electric-fencing-kit-1-mile",
    price: 189.00,
    compareAtPrice: 229.00,
    category: "Fencing & Livestock",
    subcategory: "Electric Fencing",
    image: "https://images.unsplash.com/photo-1500076656116-558758c991c1?w=800&q=80",
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    badge: "Deal",
    description: "Complete electric fencing system. Includes energizer, posts, wire, and insulators.",
  },
  {
    id: "p4",
    name: "Husky 2000lb Livestock Gate - 12ft",
    slug: "husky-livestock-gate-12ft",
    price: 159.00,
    compareAtPrice: 179.00,
    category: "Fencing & Livestock",
    subcategory: "Gates & Panels",
    image: "https://images.unsplash.com/photo-1500076656116-558758c991c1?w=800&q=80",
    rating: 4.9,
    reviewCount: 67,
    inStock: true,
    badge: "Popular",
    description: "Heavy-duty 12ft livestock gate. Powder coated for maximum durability.",
  },
  {
    id: "p16",
    name: "Red Brand 4-Point Barbed Wire 1320ft",
    slug: "red-brand-4-point-barbed-wire",
    price: 74.99,
    category: "Fencing & Livestock",
    subcategory: "Barbed Wire",
    image: "https://images.unsplash.com/photo-1500076656116-558758c991c1?w=800&q=80",
    rating: 4.6,
    reviewCount: 112,
    inStock: true,
    description: "Heavy duty 12.5 gauge 4-point barbed wire. 1320 ft roll.",
  },
  {
    id: "p17",
    name: "T-Posts 6ft Green - 10 Pack",
    slug: "t-posts-6ft-10-pack",
    price: 64.99,
    category: "Fencing & Livestock",
    subcategory: "Posts & Stakes",
    image: "https://picsum.photos/id/201/600/600",
    rating: 4.8,
    reviewCount: 203,
    inStock: true,
    badge: "Best Seller",
    description: "Heavy gauge painted T-posts with anchor plates. Sold in bundles of 10.",
  },
  {
    id: "p18",
    name: "High Tensile Smooth Wire 4000ft",
    slug: "high-tensile-smooth-wire-4000ft",
    price: 119.00,
    category: "Fencing & Livestock",
    subcategory: "Smooth Wire",
    image: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800&q=80",
    rating: 4.5,
    reviewCount: 58,
    inStock: true,
    description: "12.5 gauge high tensile smooth wire for permanent fencing.",
  },
  {
    id: "p19",
    name: "Powder River Classic Squeeze Chute",
    slug: "powder-river-classic-squeeze-chute",
    price: 2890.00,
    category: "Fencing & Livestock",
    subcategory: "Handling Equipment",
    image: "https://picsum.photos/id/106/600/600",
    rating: 4.9,
    reviewCount: 29,
    inStock: true,
    description: "Heavy duty manual squeeze chute with palpation cage. Built for Canadian ranches.",
  },
  {
    id: "p20",
    name: "Farm Boy 5ft Sheep & Goat Panel 10ft",
    slug: "farm-boy-sheep-goat-panel",
    price: 89.00,
    category: "Fencing & Livestock",
    subcategory: "Gates & Panels",
    image: "https://picsum.photos/id/292/600/600",
    rating: 4.4,
    reviewCount: 41,
    inStock: true,
    description: "6 gauge welded wire panels ideal for sheep, goats and small livestock.",
  },
  {
    id: "p21",
    name: "Gallagher SmartFix Fault Finder",
    slug: "gallagher-smartfix-fault-finder",
    price: 129.00,
    category: "Fencing & Livestock",
    subcategory: "Electric Fencing",
    image: "https://picsum.photos/id/180/600/600",
    rating: 4.7,
    reviewCount: 76,
    inStock: true,
    description: "Digital fault finder for locating shorts on electric fence lines quickly.",
  },

  // === CROP INPUTS (7 products) ===
  {
    id: "p5",
    name: "Canola Seed - Invigor L343PC 50lb Bag",
    slug: "canola-seed-invigor-l343pc",
    price: 245.00,
    category: "Crop Inputs",
    subcategory: "Seed",
    image: "https://picsum.photos/id/312/600/600",
    rating: 4.6,
    reviewCount: 41,
    inStock: true,
    description: "High-yielding LibertyLink canola seed with excellent standability.",
  },
  {
    id: "p22",
    name: "Roundup WeatherMAX 1L",
    slug: "roundup-weathermax-1l",
    price: 48.99,
    category: "Crop Inputs",
    subcategory: "Herbicides",
    image: "https://picsum.photos/id/201/600/600",
    rating: 4.8,
    reviewCount: 134,
    inStock: true,
    badge: "Best Seller",
    description: "Premium glyphosate herbicide with superior performance in tough conditions.",
  },
  {
    id: "p23",
    name: "46-0-0 Urea Fertilizer 50lb",
    slug: "urea-fertilizer-50lb",
    price: 32.50,
    category: "Crop Inputs",
    subcategory: "Fertilizer",
    image: "https://picsum.photos/id/292/600/600",
    rating: 4.3,
    reviewCount: 67,
    inStock: true,
    description: "High nitrogen granular fertilizer for spring and fall applications.",
  },
  {
    id: "p24",
    name: "Dekalb DKC33-78RIB Corn Seed 80k",
    slug: "dekalb-dkc33-corn-seed",
    price: 289.00,
    category: "Crop Inputs",
    subcategory: "Seed",
    image: "https://picsum.photos/id/312/600/600",
    rating: 4.7,
    reviewCount: 38,
    inStock: true,
    description: "SmartStax RIB Complete corn hybrid with excellent yield potential.",
  },
  {
    id: "p25",
    name: "Prosaro Fungicide 1L",
    slug: "prosaro-fungicide-1l",
    price: 142.00,
    category: "Crop Inputs",
    subcategory: "Fungicides",
    image: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800&q=80",
    rating: 4.5,
    reviewCount: 52,
    inStock: true,
    description: "Broad spectrum fungicide for wheat and barley disease control.",
  },
  {
    id: "p26",
    name: "Boron 10% Liquid Micronutrient 10L",
    slug: "boron-liquid-micronutrient",
    price: 67.99,
    category: "Crop Inputs",
    subcategory: "Micronutrients",
    image: "https://picsum.photos/id/251/600/600",
    rating: 4.2,
    reviewCount: 29,
    inStock: true,
    description: "Essential boron for canola and alfalfa production.",
  },
  {
    id: "p27",
    name: "Edge Herbicide 2.25L",
    slug: "edge-herbicide-225l",
    price: 89.99,
    category: "Crop Inputs",
    subcategory: "Herbicides",
    image: "https://picsum.photos/id/180/600/600",
    rating: 4.6,
    reviewCount: 48,
    inStock: true,
    description: "Pre-emergent herbicide for canola and pulse crops.",
  },

  // === WORKWEAR & BOOTS (7 products) ===
  {
    id: "p3",
    name: "Wrangler Riggs Workwear Jeans - Relaxed Fit",
    slug: "wrangler-riggs-workwear-jeans",
    price: 64.99,
    category: "Workwear & Boots",
    subcategory: "Men's Workwear",
    image: "https://picsum.photos/id/1005/600/600",
    rating: 4.5,
    reviewCount: 203,
    inStock: true,
    description: "Durable, reinforced work jeans built for the toughest farm conditions.",
    variants: [
      { type: "Waist", options: ["32", "34", "36", "38"] },
      { type: "Length", options: ["30", "32", "34"] },
    ],
  },
  {
    id: "p6",
    name: "Carhartt Arctic Quilt Lined Jacket",
    slug: "carhartt-arctic-quilt-lined-jacket",
    price: 119.99,
    category: "Workwear & Boots",
    subcategory: "Outerwear",
    image: "https://picsum.photos/id/1009/600/600",
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    badge: "Best Seller",
    description: "Warm, rugged work jacket for -30°C prairie winters.",
    variants: [{ type: "Size", options: ["M", "L", "XL", "2XL"] }],
  },
  {
    id: "p10",
    name: "Sorel Caribou Winter Boots - Mens",
    slug: "sorel-caribou-winter-boots",
    price: 189.00,
    category: "Workwear & Boots",
    subcategory: "Footwear",
    image: "https://picsum.photos/id/21/600/600",
    rating: 4.7,
    reviewCount: 112,
    inStock: true,
    description: "Legendary warmth and waterproofing for Western Canadian winters.",
    variants: [{ type: "Size", options: ["8", "9", "10", "11", "12"] }],
  },
  {
    id: "p28",
    name: "Carhartt Force Long Sleeve T-Shirt",
    slug: "carhartt-force-long-sleeve-tee",
    price: 34.99,
    category: "Workwear & Boots",
    subcategory: "Men's Workwear",
    image: "https://picsum.photos/id/1005/600/600",
    rating: 4.6,
    reviewCount: 89,
    inStock: true,
    description: "FastDry technology wicks sweat and fights odor. Built for hard work.",
    variants: [{ type: "Size", options: ["M", "L", "XL", "2XL"] }],
  },
  {
    id: "p29",
    name: "Baffin Hunter Insulated Rubber Boot",
    slug: "baffin-hunter-rubber-boot",
    price: 139.00,
    category: "Workwear & Boots",
    subcategory: "Footwear",
    image: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800&q=80",
    rating: 4.4,
    reviewCount: 63,
    inStock: true,
    description: "400g Thinsulate insulated rubber boot. Perfect for chores in wet conditions.",
  },
  {
    id: "p30",
    name: "Filson Short Lined Cruiser Vest",
    slug: "filson-lined-cruiser-vest",
    price: 165.00,
    category: "Workwear & Boots",
    subcategory: "Outerwear",
    image: "https://picsum.photos/id/1009/600/600",
    rating: 4.9,
    reviewCount: 34,
    inStock: true,
    description: "Rugged waxed cotton vest with warm wool lining. Made to last generations.",
  },
  {
    id: "p31",
    name: "Hestra Army Leather Winter Gloves",
    slug: "hestra-army-leather-gloves",
    price: 89.00,
    category: "Workwear & Boots",
    subcategory: "Gloves & Accessories",
    image: "https://picsum.photos/id/201/600/600",
    rating: 4.8,
    reviewCount: 71,
    inStock: true,
    description: "Premium leather work gloves with Thinsulate lining. Extremely durable.",
  },

  // === EQUIPMENT & TOOLS (7 products) ===
  {
    id: "p8",
    name: "T-Post Driver - Heavy Duty",
    slug: "t-post-driver-heavy-duty",
    price: 47.99,
    category: "Equipment & Tools",
    subcategory: "Fencing Tools",
    image: "https://picsum.photos/id/201/600/600",
    rating: 4.3,
    reviewCount: 52,
    inStock: true,
    description: "Professional grade T-post driver. Makes installing fence posts dramatically faster.",
  },
  {
    id: "p32",
    name: "Stihl MS 180 C-BE Chainsaw 16\"",
    slug: "stihl-ms180-chainsaw",
    price: 329.00,
    category: "Equipment & Tools",
    subcategory: "Power Tools",
    image: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800&q=80",
    rating: 4.8,
    reviewCount: 94,
    inStock: true,
    badge: "Popular",
    description: "Lightweight and powerful chainsaw perfect for firewood and ranch work.",
  },
  {
    id: "p33",
    name: "DeWalt 20V Max Cordless Impact Driver Kit",
    slug: "dewalt-20v-impact-driver-kit",
    price: 189.00,
    category: "Equipment & Tools",
    subcategory: "Power Tools",
    image: "https://picsum.photos/id/180/600/600",
    rating: 4.7,
    reviewCount: 128,
    inStock: true,
    description: "Compact 20V impact driver with 2 batteries and charger. Essential farm tool.",
  },
  {
    id: "p34",
    name: "Fiskars 28\" Splitting Axe",
    slug: "fiskars-28-splitting-axe",
    price: 54.99,
    category: "Equipment & Tools",
    subcategory: "Hand Tools",
    image: "https://picsum.photos/id/201/600/600",
    rating: 4.6,
    reviewCount: 87,
    inStock: true,
    description: "Razor sharp splitting axe with shock absorbing handle. Made in Finland.",
  },
  {
    id: "p35",
    name: "Lincoln Electric 140C MIG Welder",
    slug: "lincoln-140c-mig-welder",
    price: 649.00,
    category: "Equipment & Tools",
    subcategory: "Welding",
    image: "https://picsum.photos/id/292/600/600",
    rating: 4.9,
    reviewCount: 56,
    inStock: true,
    description: "Reliable wire feed welder for farm repairs. 120V input.",
  },
  {
    id: "p36",
    name: "Northern Tool 5-Ton Hydraulic Log Splitter",
    slug: "northern-tool-5-ton-log-splitter",
    price: 449.00,
    category: "Equipment & Tools",
    subcategory: "Power Tools",
    image: "https://picsum.photos/id/106/600/600",
    rating: 4.5,
    reviewCount: 39,
    inStock: true,
    description: "Vertical/horizontal log splitter. Perfect for the wood heat crowd.",
  },
  {
    id: "p37",
    name: "Klein Tools 41-Piece Electrician Tool Set",
    slug: "klein-tools-41-piece-set",
    price: 279.00,
    category: "Equipment & Tools",
    subcategory: "Hand Tools",
    image: "https://picsum.photos/id/180/600/600",
    rating: 4.8,
    reviewCount: 44,
    inStock: true,
    description: "Professional grade tool kit for electrical and general maintenance.",
  },

  // === ANIMAL HEALTH (6 products) ===
  {
    id: "p38",
    name: "Ivermectin Pour-On for Cattle 1L",
    slug: "ivermectin-pour-on-1l",
    price: 67.99,
    category: "Animal Health",
    subcategory: "Parasite Control",
    image: "https://picsum.photos/id/251/600/600",
    rating: 4.7,
    reviewCount: 98,
    inStock: true,
    badge: "Best Seller",
    description: "Broad spectrum parasite control for cattle. Easy pour-on application.",
  },
  {
    id: "p39",
    name: "Draxxin Injectable Antibiotic 100ml",
    slug: "draxxin-injectable-100ml",
    price: 189.00,
    category: "Animal Health",
    subcategory: "Antibiotics",
    image: "https://picsum.photos/id/292/600/600",
    rating: 4.9,
    reviewCount: 47,
    inStock: true,
    description: "Single dose treatment for bovine respiratory disease.",
  },
  {
    id: "p40",
    name: "Cydectin Pour-On for Sheep 1L",
    slug: "cydectin-pour-on-sheep",
    price: 74.50,
    category: "Animal Health",
    subcategory: "Parasite Control",
    image: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800&q=80",
    rating: 4.6,
    reviewCount: 61,
    inStock: true,
    description: "Long acting pour-on for internal and external parasites in sheep.",
  },
  {
    id: "p41",
    name: "Vetericyn Wound & Skin Care 16oz",
    slug: "vetericyn-wound-care-16oz",
    price: 28.99,
    category: "Animal Health",
    subcategory: "Wound Care",
    image: "https://picsum.photos/id/201/600/600",
    rating: 4.5,
    reviewCount: 73,
    inStock: true,
    description: "Non-toxic, pH balanced wound spray safe for all livestock.",
  },
  {
    id: "p42",
    name: "Zoetis Bovi-Shield Gold 5 Vaccine 10 Dose",
    slug: "bovi-shield-gold-5-vaccine",
    price: 42.00,
    category: "Animal Health",
    subcategory: "Vaccines",
    image: "https://picsum.photos/id/251/600/600",
    rating: 4.8,
    reviewCount: 55,
    inStock: true,
    description: "5-way respiratory vaccine for cattle. Modified live.",
  },
  {
    id: "p43",
    name: "Ultra Boss Pour-On Insecticide 1L",
    slug: "ultra-boss-pour-on-1l",
    price: 54.99,
    category: "Animal Health",
    subcategory: "Insect Control",
    image: "https://picsum.photos/id/180/600/600",
    rating: 4.4,
    reviewCount: 39,
    inStock: true,
    description: "Controls lice, horn flies, and ticks on cattle and sheep.",
  },
];

export const categories = [
  { 
    name: "Feed & Nutrition", 
    slug: "feed-nutrition", 
    image: "https://picsum.photos/id/292/600/400" 
  },
  { 
    name: "Fencing & Livestock", 
    slug: "fencing-livestock", 
    image: "https://picsum.photos/id/180/600/400" 
  },
  { 
    name: "Crop Inputs", 
    slug: "crop-inputs", 
    image: "https://picsum.photos/id/312/600/400" 
  },
  { 
    name: "Workwear & Boots", 
    slug: "workwear-boots", 
    image: "https://picsum.photos/id/1009/600/400" 
  },
  { 
    name: "Equipment & Tools", 
    slug: "equipment-tools", 
    image: "https://picsum.photos/id/160/600/400" 
  },
  { 
    name: "Animal Health", 
    slug: "animal-health", 
    image: "https://picsum.photos/id/251/600/400" 
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}
